# Pytorch Tutorial - 00

In [1]:
import torch
torch.__version__

'1.13.1'

### Tensors

- Fundamental block of Machine Learning
- Used to represent any data (images for eg) in numerical means

For example, an image could be represented as a tensor with shape `[3, 224, 224]` which would mean `[colour_channels, width, height]` as in the image has 3 colours channel (RGB), and a width and height of 224 pixels each.

### Scalars

A scaler is a simple number. In tensor talk, it is a zero dimensional tensor.

In [2]:
#Scalar
scaler = torch.tensor(7)
scaler

tensor(7)

This prints out tensor(7) indicating that scaler is a single number, but of type `torch.Tensor`

In [3]:
scaler.ndim

0

In [4]:
# To retrieve the number from the scaler, we use scaler.item method
scaler.item()

7

### Vector

- A vector is a one-dimensional tensor but can contain many numbers.
- It is flexible in what all it can represent.
- For example, a single vector `[3,2]` could be used to represent `[bathrooms, bedrooms]` in our house or `[3,2,2]` could be used to represent `[bathrooms, bedrooms, car_spaces]` in our house.

In [5]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
# Dimensions of a vector
vector.ndim

1

In [8]:
# Shape of a Vector
vector.shape

torch.Size([2])

- Thus we see that the vector is one-dimensional (like a 1D-array) [no. of square brackets]
- Its shape is 2 because it has 2 elements in its array/vector or in its square brackets.

### Matrix
A matrix is flexible like a vector, just has more dimensions.

In [11]:
MATRIX = torch.tensor([[3,4],
                        [5,6]])
MATRIX

tensor([[3, 4],
        [5, 6]])

In [13]:
print(MATRIX.shape) #Shape is 2,2 cause of 2 elements in each vector
print(MATRIX.ndim) # 2 dimensional

torch.Size([2, 2])
2


In [21]:
# Any higher dimension can also be created similiarly and is called a tensor
TENSOR = torch.tensor([[[1,2,3],
                      [3,6,9],
                       [2,8,10]]])
TENSOR                      # Given tensor represents [day of week, steak sales, no of ]

tensor([[[ 1,  2,  3],
         [ 3,  6,  9],
         [ 2,  8, 10]]])

In [22]:
print(TENSOR.shape) #Shape goes outer to inner, thats why it returns 1,3,3
print(TENSOR.ndim)

torch.Size([1, 3, 3])
3


## Random Tensors

In ML, we hardly generate hardcoded tensors like these. But rather a ML model starts off with large random tensors of numbers and adjusts them to make the data look better

### Essence
`Start with data --> look at data --> update random numbers --> look at data --> update random numbers....`


In [23]:
# Create random tensor of size (3,4)
rand_tensor = torch.rand(size=(3,4))
rand_tensor, rand_tensor.dtype

(tensor([[0.1944, 0.4664, 0.8440, 0.9590],
         [0.9030, 0.6523, 0.2269, 0.5426],
         [0.3525, 0.3810, 0.5972, 0.0554]]),
 torch.float32)

In [25]:
# Creating random tensor within the [3,224,224] image size
rand_tensor = torch.rand(size = (3, 224, 224))
print(rand_tensor) 
print(rand_tensor.shape)
print(rand_tensor.ndim)
print(rand_tensor.dtype)

tensor([[[0.7846, 0.5648, 0.5865,  ..., 0.7889, 0.0196, 0.6634],
         [0.0461, 0.7951, 0.6063,  ..., 0.0055, 0.0087, 0.9430],
         [0.2289, 0.3440, 0.2999,  ..., 0.7185, 0.3451, 0.9886],
         ...,
         [0.8879, 0.9645, 0.4401,  ..., 0.0165, 0.3377, 0.9539],
         [0.4487, 0.6370, 0.9277,  ..., 0.0736, 0.0055, 0.8208],
         [0.5728, 0.0961, 0.3055,  ..., 0.9921, 0.7182, 0.7228]],

        [[0.9414, 0.4570, 0.4185,  ..., 0.8165, 0.9186, 0.6070],
         [0.8885, 0.0665, 0.0807,  ..., 0.1203, 0.5337, 0.5413],
         [0.9315, 0.4849, 0.2729,  ..., 0.6598, 0.4061, 0.5451],
         ...,
         [0.3384, 0.5537, 0.0107,  ..., 0.1463, 0.5034, 0.0200],
         [0.7138, 0.7953, 0.5236,  ..., 0.3994, 0.4343, 0.4478],
         [0.6151, 0.4382, 0.7057,  ..., 0.6331, 0.1297, 0.2321]],

        [[0.0679, 0.2860, 0.5341,  ..., 0.4046, 0.4913, 0.2484],
         [0.7166, 0.0618, 0.5459,  ..., 0.6997, 0.7790, 0.0026],
         [0.6875, 0.2783, 0.8471,  ..., 0.2355, 0.9336, 0.

In [26]:
# Tensor of all zeroes
tensor_zeroes = torch.zeros(size = (3,4))
tensor_zeroes, tensor_zeroes.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [27]:
# Tensor of all ones
tensor_ones = torch.ones(size = (3,4))
tensor_ones, tensor_ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [29]:
# We can create using torch.arange(start, end, step) like python ranges
tensor_range = torch.arange(start = 0, end = 10, step = 1)
tensor_range

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
# Create a tensor filled with zeros or ones in the same shape as input using zeros_like(input) & ones_like(input)
tensor_sim = torch.zeros_like(input = tensor_range)
tensor_sim

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes
`torch.tensor()` method has additional arguments for dtype (default is torch.float32), device (which uses default tensor type) and requires_grad

In [32]:
# Other datatypes include for eg float16, float64, etc.
tensor_mytype = torch.tensor([[3,6,7]],
                                dtype=torch.float64)
tensor_mytype

tensor([[3., 6., 7.]], dtype=torch.float64)

In [33]:
# Getting Information from Tensors

some_tensor = torch.rand(size=(3,4))

print(f'Tensor : {some_tensor}')
print(f'Tensor Shape : {some_tensor.shape}')
print(f'Tensor Datatype : {some_tensor.dtype}')
print(f'Tensor Device : {some_tensor.device}')

Tensor : tensor([[0.9278, 0.8041, 0.4785, 0.3828],
        [0.8234, 0.6541, 0.8517, 0.6904],
        [0.5927, 0.9732, 0.3959, 0.5329]])
Tensor Shape : torch.Size([3, 4])
Tensor Datatype : torch.float32
Tensor Device : cpu


## Manipulating Tensors

- Like numpy arrays, we have basic operations on these tensors like addition, subtraction, multiplication wherein on re-assignment

In [35]:
a = torch.tensor([1,2,3])
b = a @ a
b


tensor(14)